### ISSUE TITLE
GET arguments instead of cookie for station list?

### ISSUE THREAD

**Issue by marksz** [jqin/gasbuddy-scraper#1]
I love your demo!  I find it tedious to search Gasbuddy for the best stations along my routes, and have found that be best ones seem to rotate among a handful of stations.  I thought about putting my route with all possible stations in a Google sheet, but couldn't figure out how to get current gas prices to update there.  Your demo page puts the numbers in a table which almost makes it easy to access from a spreadsheet!  The problem is the table grab function will be run by the host, and not have my client cookie.  If I could put the station list in the URL as arguments, then I'd have the solution I'm looking for!

My coding skills are not up to forking your project, but I would be willing to try and help add this.  
P.S.  The zip code doesn't seem to do anything in the demo.  What am I missing?

**Comment by jqin** [comment]
The zip code box should work now. It will add the 5 gas stations that come up in the search. Thanks for reporting it.

You can already put the station list in the URL as arguments. The endpoint you can use is:
`controller.php?action=station&ids=XXX,YYY,ZZZ` which will return the json encoded output.

**Comment by marksz** [comment]
Fantastic!  Thank you so much!!

I hope to create a spreadsheet with a long road trip I do every few months,
and see at a glance where I'll stop for gas that trip!
